//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace n_Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("n_Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good bye my friend .
        /// </summary>
        public static string breakup_massage {
            get {
                return ResourceManager.GetString("breakup_massage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which action would you like to do.
        /// </summary>
        public static string choose_action {
            get {
                return ResourceManager.GetString("choose_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to do another action
        ///1) yes 
        ///2) no.
        /// </summary>
        public static string continue_massage {
            get {
                return ResourceManager.GetString("continue_massage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You enter invalid number, please enter again..
        /// </summary>
        public static string invalid_integer {
            get {
                return ResourceManager.GetString("invalid_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You choose an option that doesn&apos;t exist.
        /// </summary>
        public static string invalid_menu_choice {
            get {
                return ResourceManager.GetString("invalid_menu_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new vehicle.
        /// </summary>
        public static string menu_options_1 {
            get {
                return ResourceManager.GetString("menu_options_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show list of all plates.
        /// </summary>
        public static string menu_options_2 {
            get {
                return ResourceManager.GetString("menu_options_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change vehicle properties.
        /// </summary>
        public static string menu_options_3 {
            get {
                return ResourceManager.GetString("menu_options_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inflating vehicle wheel.
        /// </summary>
        public static string menu_options_4 {
            get {
                return ResourceManager.GetString("menu_options_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel vehicle.
        /// </summary>
        public static string menu_options_5 {
            get {
                return ResourceManager.GetString("menu_options_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge vehicle.
        /// </summary>
        public static string menu_options_6 {
            get {
                return ResourceManager.GetString("menu_options_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all vehicles details.
        /// </summary>
        public static string menu_options_7 {
            get {
                return ResourceManager.GetString("menu_options_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string menu_options_8 {
            get {
                return ResourceManager.GetString("menu_options_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string title_car {
            get {
                return ResourceManager.GetString("title_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Car.
        /// </summary>
        public static string title_electric_car {
            get {
                return ResourceManager.GetString("title_electric_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Motorcycle.
        /// </summary>
        public static string title_electric_motorcycle {
            get {
                return ResourceManager.GetString("title_electric_motorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle.
        /// </summary>
        public static string title_motorcycle {
            get {
                return ResourceManager.GetString("title_motorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        public static string title_truck {
            get {
                return ResourceManager.GetString("title_truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the best Garage in the city.
        /// </summary>
        public static string welcome_massage {
            get {
                return ResourceManager.GetString("welcome_massage", resourceCulture);
            }
        }
    }
}
