//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace n_Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("n_Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much fuel would you like to fuel.
        /// </summary>
        public static string amount_fuel_massage {
            get {
                return ResourceManager.GetString("amount_fuel_massage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the amount you want to fill the tires:.
        /// </summary>
        public static string amount_to_fill_tire {
            get {
                return ResourceManager.GetString("amount_to_fill_tire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery level: {0}
        ///.
        /// </summary>
        public static string battery_level {
            get {
                return ResourceManager.GetString("battery_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good bye my friend .
        /// </summary>
        public static string breakup_massage {
            get {
                return ResourceManager.GetString("breakup_massage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car color: {0}
        ///.
        /// </summary>
        public static string car_color {
            get {
                return ResourceManager.GetString("car_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current status is {0}, Please choose new status for car.
        /// </summary>
        public static string change_status_options {
            get {
                return ResourceManager.GetString("change_status_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which action would you like to do.
        /// </summary>
        public static string choose_action {
            get {
                return ResourceManager.GetString("choose_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose your car color.
        /// </summary>
        public static string choose_car_color {
            get {
                return ResourceManager.GetString("choose_car_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose door number for your car.
        /// </summary>
        public static string choose_door_number {
            get {
                return ResourceManager.GetString("choose_door_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the status for new vehicle.
        /// </summary>
        public static string choose_status_of_vehicle {
            get {
                return ResourceManager.GetString("choose_status_of_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose type of fuel you want to fuel.
        /// </summary>
        public static string choose_type_of_fuel {
            get {
                return ResourceManager.GetString("choose_type_of_fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose vehicle type:.
        /// </summary>
        public static string choose_type_of_vehicle {
            get {
                return ResourceManager.GetString("choose_type_of_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to do another action
        ///1) yes 
        ///2) no.
        /// </summary>
        public static string continue_massage {
            get {
                return ResourceManager.GetString("continue_massage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the details of new vehicle you want to add to the garage:.
        /// </summary>
        public static string create_new_vehicle {
            get {
                return ResourceManager.GetString("create_new_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel level: {0}
        ///.
        /// </summary>
        public static string current_fuel_level {
            get {
                return ResourceManager.GetString("current_fuel_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door number: {0}
        ///.
        /// </summary>
        public static string door_number {
            get {
                return ResourceManager.GetString("door_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric vehicle.
        /// </summary>
        public static string electric_vehicle_battery {
            get {
                return ResourceManager.GetString("electric_vehicle_battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter engine capacity.
        /// </summary>
        public static string engine_capacity_massage {
            get {
                return ResourceManager.GetString("engine_capacity_massage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter model name:.
        /// </summary>
        public static string enter_model_name {
            get {
                return ResourceManager.GetString("enter_model_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter owner name:.
        /// </summary>
        public static string enter_owner_name {
            get {
                return ResourceManager.GetString("enter_owner_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number:.
        /// </summary>
        public static string enter_phone_number {
            get {
                return ResourceManager.GetString("enter_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter plate number:.
        /// </summary>
        public static string enter_plate_number {
            get {
                return ResourceManager.GetString("enter_plate_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter wheel manufacturer name:.
        /// </summary>
        public static string enter_wheel_manufacturer {
            get {
                return ResourceManager.GetString("enter_wheel_manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using out application, hope to see you soon!.
        /// </summary>
        public static string exit_program_message {
            get {
                return ResourceManager.GetString("exit_program_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string false_option {
            get {
                return ResourceManager.GetString("false_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five doors.
        /// </summary>
        public static string five_doors {
            get {
                return ResourceManager.GetString("five_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string fixed_title {
            get {
                return ResourceManager.GetString("fixed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four doors.
        /// </summary>
        public static string four_doors {
            get {
                return ResourceManager.GetString("four_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel type: {0}
        ///.
        /// </summary>
        public static string fuel_type {
            get {
                return ResourceManager.GetString("fuel_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter License number.
        /// </summary>
        public static string get_license_massage {
            get {
                return ResourceManager.GetString("get_license_massage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporting hazardous materials? {0}
        ///.
        /// </summary>
        public static string hazardous_materials {
            get {
                return ResourceManager.GetString("hazardous_materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InRapair.
        /// </summary>
        public static string inrepair_title {
            get {
                return ResourceManager.GetString("inrepair_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You enter invalid number, please enter again..
        /// </summary>
        public static string invalid_integer {
            get {
                return ResourceManager.GetString("invalid_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You choose an option that doesn&apos;t exist.
        /// </summary>
        public static string invalid_menu_choice {
            get {
                return ResourceManager.GetString("invalid_menu_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string license_a {
            get {
                return ResourceManager.GetString("license_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1.
        /// </summary>
        public static string license_a1 {
            get {
                return ResourceManager.GetString("license_a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A2.
        /// </summary>
        public static string license_a2 {
            get {
                return ResourceManager.GetString("license_a2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string license_b {
            get {
                return ResourceManager.GetString("license_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License type: {0}\n.
        /// </summary>
        public static string license_type {
            get {
                return ResourceManager.GetString("license_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===============================.
        /// </summary>
        public static string line_brake {
            get {
                return ResourceManager.GetString("line_brake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}) {1}.
        /// </summary>
        public static string menu_format {
            get {
                return ResourceManager.GetString("menu_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new vehicle.
        /// </summary>
        public static string menu_options_1 {
            get {
                return ResourceManager.GetString("menu_options_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show list of all plates.
        /// </summary>
        public static string menu_options_2 {
            get {
                return ResourceManager.GetString("menu_options_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change vehicle properties.
        /// </summary>
        public static string menu_options_3 {
            get {
                return ResourceManager.GetString("menu_options_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inflating vehicle wheel.
        /// </summary>
        public static string menu_options_4 {
            get {
                return ResourceManager.GetString("menu_options_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel vehicle.
        /// </summary>
        public static string menu_options_5 {
            get {
                return ResourceManager.GetString("menu_options_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge vehicle.
        /// </summary>
        public static string menu_options_6 {
            get {
                return ResourceManager.GetString("menu_options_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all vehicles details.
        /// </summary>
        public static string menu_options_7 {
            get {
                return ResourceManager.GetString("menu_options_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string menu_options_8 {
            get {
                return ResourceManager.GetString("menu_options_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name: {0}
        ///.
        /// </summary>
        public static string model_name {
            get {
                return ResourceManager.GetString("model_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octan 95.
        /// </summary>
        public static string octan_95 {
            get {
                return ResourceManager.GetString("octan_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octan 96.
        /// </summary>
        public static string octan_96 {
            get {
                return ResourceManager.GetString("octan_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octan 98.
        /// </summary>
        public static string octan_98 {
            get {
                return ResourceManager.GetString("octan_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but you entered invalid value..
        /// </summary>
        public static string out_of_range {
            get {
                return ResourceManager.GetString("out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is more than maximum..
        /// </summary>
        public static string out_of_range_max {
            get {
                return ResourceManager.GetString("out_of_range_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is less than minimum..
        /// </summary>
        public static string out_of_range_min {
            get {
                return ResourceManager.GetString("out_of_range_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner name: {0}
        ///.
        /// </summary>
        public static string owner_name {
            get {
                return ResourceManager.GetString("owner_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner phone number: {0}
        ///.
        /// </summary>
        public static string owner_phone_number {
            get {
                return ResourceManager.GetString("owner_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string paid_title {
            get {
                return ResourceManager.GetString("paid_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but the plate {0} didn&apos;t find in our system!.
        /// </summary>
        public static string plate_didnt_found {
            get {
                return ResourceManager.GetString("plate_didnt_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle with plate number {0} is already found in system, Move vehicle to status repair.
        /// </summary>
        public static string plate_found {
            get {
                return ResourceManager.GetString("plate_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate number: {0}
        ///.
        /// </summary>
        public static string plate_number {
            get {
                return ResourceManager.GetString("plate_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of remaining energy: {0}
        ///.
        /// </summary>
        public static string remaning_energy {
            get {
                return ResourceManager.GetString("remaning_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the capacity level of engine (cc).
        /// </summary>
        public static string set_engine_capacity {
            get {
                return ResourceManager.GetString("set_engine_capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the capacity level of turck&apos;s trunk.
        /// </summary>
        public static string set_truck_capacity_level {
            get {
                return ResourceManager.GetString("set_truck_capacity_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine capacity: {0} cc
        ///.
        /// </summary>
        public static string show_engine_capacity {
            get {
                return ResourceManager.GetString("show_engine_capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soler.
        /// </summary>
        public static string soler {
            get {
                return ResourceManager.GetString("soler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third doors.
        /// </summary>
        public static string three_doors {
            get {
                return ResourceManager.GetString("three_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string title_black {
            get {
                return ResourceManager.GetString("title_black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string title_blue {
            get {
                return ResourceManager.GetString("title_blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string title_car {
            get {
                return ResourceManager.GetString("title_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Car.
        /// </summary>
        public static string title_electric_car {
            get {
                return ResourceManager.GetString("title_electric_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Motorcycle.
        /// </summary>
        public static string title_electric_motorcycle {
            get {
                return ResourceManager.GetString("title_electric_motorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string title_gray {
            get {
                return ResourceManager.GetString("title_gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle.
        /// </summary>
        public static string title_motorcycle {
            get {
                return ResourceManager.GetString("title_motorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string title_red {
            get {
                return ResourceManager.GetString("title_red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        public static string title_truck {
            get {
                return ResourceManager.GetString("title_truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string true_option {
            get {
                return ResourceManager.GetString("true_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trunk capacity: {0}
        ///.
        /// </summary>
        public static string trunk_capacity {
            get {
                return ResourceManager.GetString("trunk_capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tried to charge fuel based vehicle, that cannot be excute!.
        /// </summary>
        public static string try_to_charge_fuel_vehicle {
            get {
                return ResourceManager.GetString("try_to_charge_fuel_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tried to fuel electric vehicle, that cannot be excute!.
        /// </summary>
        public static string try_to_fuel_electric_vehicle {
            get {
                return ResourceManager.GetString("try_to_fuel_electric_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but you tried to fuel with the wrong type of fuel, we cannot do that!.
        /// </summary>
        public static string try_to_fuel_other_type_of_fuel {
            get {
                return ResourceManager.GetString("try_to_fuel_other_type_of_fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two doors.
        /// </summary>
        public static string two_doors {
            get {
                return ResourceManager.GetString("two_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle status: {0}
        ///.
        /// </summary>
        public static string vehicle_status {
            get {
                return ResourceManager.GetString("vehicle_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the best Garage in the city.
        /// </summary>
        public static string welcome_massage {
            get {
                return ResourceManager.GetString("welcome_massage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel current pressure: {0}
        ///.
        /// </summary>
        public static string wheel_current_pressure {
            get {
                return ResourceManager.GetString("wheel_current_pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel manufacturer: {0}
        ///.
        /// </summary>
        public static string wheel_manufacturer {
            get {
                return ResourceManager.GetString("wheel_manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will transporting hazardous materials?.
        /// </summary>
        public static string will_delivery_materials {
            get {
                return ResourceManager.GetString("will_delivery_materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
