//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reversi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reversi.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string black_color {
            get {
                return ResourceManager.GetString("black_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered wrong board size, please try again.
        /// </summary>
        public static string board_size_invalid {
            get {
                return ResourceManager.GetString("board_size_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose color for first player:
        ///1) White
        ///2) Black.
        /// </summary>
        public static string choose_color {
            get {
                return ResourceManager.GetString("choose_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the column of your chosen square.
        /// </summary>
        public static string choose_column {
            get {
                return ResourceManager.GetString("choose_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the cordinate you want.
        /// </summary>
        public static string choose_cord {
            get {
                return ResourceManager.GetString("choose_cord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the row of your chosen square.
        /// </summary>
        public static string choose_row {
            get {
                return ResourceManager.GetString("choose_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the size of the matrix that you want? (choose 6 or 8).
        /// </summary>
        public static string choose_size_of_board {
            get {
                return ResourceManager.GetString("choose_size_of_board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string computer_name {
            get {
                return ResourceManager.GetString("computer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draw.
        /// </summary>
        public static string draw {
            get {
                return ResourceManager.GetString("draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a draw!.
        /// </summary>
        public static string end_game_draw {
            get {
                return ResourceManager.GetString("end_game_draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Won!! ({1},{2}) ({3}/{4}).
        /// </summary>
        public static string end_game_winner_string_1 {
            get {
                return ResourceManager.GetString("end_game_winner_string_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like another round?.
        /// </summary>
        public static string end_game_winner_string_2 {
            get {
                return ResourceManager.GetString("end_game_winner_string_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name:.
        /// </summary>
        public static string enter_name {
            get {
                return ResourceManager.GetString("enter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your opponent name:.
        /// </summary>
        public static string enter_name_of_player_two {
            get {
                return ResourceManager.GetString("enter_name_of_player_two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered invalid column, please try again.
        /// </summary>
        public static string error_enter_invalid_column {
            get {
                return ResourceManager.GetString("error_enter_invalid_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered invalid cords, please try again.
        /// </summary>
        public static string error_enter_invalid_cord {
            get {
                return ResourceManager.GetString("error_enter_invalid_cord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered invalid row, please try again.
        /// </summary>
        public static string error_enter_invalid_row {
            get {
                return ResourceManager.GetString("error_enter_invalid_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered invalid number, please try again.
        /// </summary>
        public static string error_enter_valid_integer {
            get {
                return ResourceManager.GetString("error_enter_valid_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Computer.
        /// </summary>
        public static string first_computer_name {
            get {
                return ResourceManager.GetString("first_computer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Othello - {0}&apos;s Turn.
        /// </summary>
        public static string form_title_turn {
            get {
                return ResourceManager.GetString("form_title_turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Othello.
        /// </summary>
        public static string game_basic_title {
            get {
                return ResourceManager.GetString("game_basic_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You choose invalid square, please choose other one..
        /// </summary>
        public static string not_valid_square {
            get {
                return ResourceManager.GetString("not_valid_square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to play again? press Y/N.
        /// </summary>
        public static string play_again {
            get {
                return ResourceManager.GetString("play_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t have any available moves, the turn goes to the next player!.
        /// </summary>
        public static string player_dont_have_available_moves {
            get {
                return ResourceManager.GetString("player_dont_have_available_moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s turn, please choose your cords.
        /// </summary>
        public static string player_is_playing {
            get {
                return ResourceManager.GetString("player_is_playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for playing, Hope to see you soon!.
        /// </summary>
        public static string player_quit_game {
            get {
                return ResourceManager.GetString("player_quit_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Score: {1}.
        /// </summary>
        public static string player_score {
            get {
                return ResourceManager.GetString("player_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string white_color {
            get {
                return ResourceManager.GetString("white_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winner is {0} !.
        /// </summary>
        public static string winner_declaration {
            get {
                return ResourceManager.GetString("winner_declaration", resourceCulture);
            }
        }
    }
}
