//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArgumentsKeysets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArgumentsKeysets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Garage.ArgumentsKeysets", typeof(ArgumentsKeysets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car_color.
        /// </summary>
        public static string sr_KeyCarColor {
            get {
                return ResourceManager.GetString("sr_KeyCarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current_energy.
        /// </summary>
        public static string sr_KeyCurrentEnergyLevel {
            get {
                return ResourceManager.GetString("sr_KeyCurrentEnergyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current_wheel_pressure.
        /// </summary>
        public static string sr_KeyCurrentWheelPressure {
            get {
                return ResourceManager.GetString("sr_KeyCurrentWheelPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delivery_materials.
        /// </summary>
        public static string sr_KeyDeliveryMaterials {
            get {
                return ResourceManager.GetString("sr_KeyDeliveryMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engine_capacity.
        /// </summary>
        public static string sr_KeyEngineCapacity {
            get {
                return ResourceManager.GetString("sr_KeyEngineCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to license_type.
        /// </summary>
        public static string sr_KeyLicenseType {
            get {
                return ResourceManager.GetString("sr_KeyLicenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max_battery_time.
        /// </summary>
        public static string sr_KeyMaxBatteryTime {
            get {
                return ResourceManager.GetString("sr_KeyMaxBatteryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max_fuel_level.
        /// </summary>
        public static string sr_KeyMaxFuelLevel {
            get {
                return ResourceManager.GetString("sr_KeyMaxFuelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max_wheel_pressure.
        /// </summary>
        public static string sr_KeyMaxWheelPressure {
            get {
                return ResourceManager.GetString("sr_KeyMaxWheelPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model_name.
        /// </summary>
        public static string sr_KeyModelName {
            get {
                return ResourceManager.GetString("sr_KeyModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to num_of_door.
        /// </summary>
        public static string sr_KeyNumberOfDoors {
            get {
                return ResourceManager.GetString("sr_KeyNumberOfDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to num_of_wheels.
        /// </summary>
        public static string sr_KeyNumberOfWheels {
            get {
                return ResourceManager.GetString("sr_KeyNumberOfWheels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to num_of_wheels.
        /// </summary>
        public static string sr_KeyNumOfWheels {
            get {
                return ResourceManager.GetString("sr_KeyNumOfWheels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owner_name.
        /// </summary>
        public static string sr_KeyOwnerName {
            get {
                return ResourceManager.GetString("sr_KeyOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone_number.
        /// </summary>
        public static string sr_KeyPhoneNumber {
            get {
                return ResourceManager.GetString("sr_KeyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plate_number.
        /// </summary>
        public static string sr_KeyPlateNumber {
            get {
                return ResourceManager.GetString("sr_KeyPlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicle_status.
        /// </summary>
        public static string sr_KeyRepairStatus {
            get {
                return ResourceManager.GetString("sr_KeyRepairStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to truck_capacity.
        /// </summary>
        public static string sr_KeyTruckCapacity {
            get {
                return ResourceManager.GetString("sr_KeyTruckCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to energy_type.
        /// </summary>
        public static string sr_KeyTypeOfEnergy {
            get {
                return ResourceManager.GetString("sr_KeyTypeOfEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type_of_vehicle.
        /// </summary>
        public static string sr_KeyTypeOfVehicle {
            get {
                return ResourceManager.GetString("sr_KeyTypeOfVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wheel_manufacturer.
        /// </summary>
        public static string sr_KeyWheelManufacturer {
            get {
                return ResourceManager.GetString("sr_KeyWheelManufacturer", resourceCulture);
            }
        }
    }
}
